TEXTS = {
    "CZ": {
        "title": "SPC Monitor - Linka A",
        "project": "Projekt",
        "shift": "Směna",
        "timer": "Další měření za:",
        "btn_measure": "ZADAT MĚŘENÍ",
        "btn_exit": "UKONČIT",
        "lbl_operator": "Operátor:",
        "lbl_value": "Naměřená hodnota (g):",
        "lbl_value_without_glue": "Naměřená hodnota bez lepidla (g):",
        "lbl_value_with_glue": "Naměřená hodnota s lepidlem (g):",
        "btn_save": "ULOŽIT ZÁZNAM",
        "btn_read_scale": "NAČÍST VÁHU (BT)",
        "alert_title": "ČAS NA MĚŘENÍ!",
        "spc_trend": "SPC Trend",
        "measure": " NOVÉ MĚŘENÍ",
        "exit": "UKONČIT",
        "project_type": "Typ projektu:",
        "remaining_time": "ZBÝVAJÍCÍ ČAS DO MĚŘENÍ",
        "settings": "Nastavení",
        "language": "Jazyk", 
        "line": "Linka",
        "big_title": "Regulace hmotnosti lepidla pomocí SPC",
        "target": "Nominální hodnota",
        "usl": "USL",
        "lsl": "LSL",
        "timer_minutes": "Časovač",
        "appearance_mode": "Vzhled zobrazení",
        "color_theme": "Barevné téma",
        "general_settings": "Obecné nastavení",
        "limits_spc": "Limity & SPC",
        "warning_limits_spc": "Varování limity SPC",
        "error_lsl_must_be_less_usl": "Chyba: LSL musí být menší než USL!",
        "error_invalid_numbers": "Chyba: Neplatné čísla!",
        "theme_blue": "Modré",
        "theme_dark_blue": "Tmavě modré",
        "theme_green": "Zelené",
        "show_seconds": "Zobrazit sekundy (pouze testování)",
        "alert_title_shift": "Varování směny",
        "shift_warning_message": "Aktuální směna není nastavena. Prosím vyberte správnou směnu.",
        "add_new_model": "PŘIDAT NOVÝ MODEL",
        "model_setup_title": "Nastavení modelu",
        "select_model": "Model",
        "save_new_model": "ULOŽIT MODEL",
        "select_model_example": "např. X254",
        "select_car": "Značka",
        "units_minutes": "min", 
        "saved_models": "Uložené modely:",
        "edit_model": "Upravit model",
        "delete_model": "Smazat model",
        "enter_password": "Zadejte heslo",
        "warning_delete_model": "Opravdu chcete smazat model '{model}'? Tato akce je nevratná.",
        "error_cannot_delete_active_model": "Chyba: Nelze smazat právě aktivní model!",
        "warning": "Varování",
        "error": "Chyba",
        "confirm": "Potvrdit",
        "cancel": "Zrušit",
        "no_model_selected": "Nemáte vybraný žádný model.\n\nProsím vyberte model ze seznamu vlevo nebo vytvořte nový.",
        "calibration": "Kalibrace",
        "current_shift": "Aktuální směna: {shift_name}",
        "really_switch_model": "Opravdu přepnout model?",
        "confirm_switch_model": "Opravdu chcete začít výrobu modelu {model_name}?",
        "btn_save_general_setting": "ULOŽIT OBECNÉ NASTAVENÍ",
        "graph_time": "Čas",
        "graph_status": "Status",
        "data_and_histogram": "Data a histogram",
        "reset_view": " Domů",
        "pan": " Posun",
        "zoom": " Lupa",
        "save": "Uložit",
        "mode_light": "Světlý",
        "mode_dark": "Tmavý",
        "mode_system": "Podle systému",
        "input_dialog_title": "Vstupní dialog",
        "alert_error": "Varování",
        "error_both_weights_required": "Musíte zadat obě váhy (s lepidlem i bez)!",
        "negative_glue_weight": "Vychází záporná váha lepidla ({weight:.2f} g)!\nZkontrolujte, zda jste hodnoty neprohodili.",
        "load_no_glue_first": "Nejprve načtěte hmotnost bez lepidla",
        "delete": "Smazat",
        "confirm_delete": "Opravdu chcete smazat tento záznam?",
        "confirm_delete_multiple": "Opravdu chcete smazat vybrané záznamy (počet: {count})?",
        "record_not_found": "Záznam se v souboru CSV nepodařilo najít.\nMožná byl už smazán externě.",
        "error_writing_file": "Chyba při zapisování do souboru",
        "stat_count": "Počet měření",
        "stat_mean": "Mean (Průměr)",
        "stat_sigma": "Sigma (Std)",
        "stat_cp": "Cp (Potenciál)",
        "stat_cpk": "Cpk (Realita)",
        "stat_fix": "Fix",   # Pro "(Fix)"
        "stat_auto": "Auto",
        "data_analysis": "Analýza dat",
        "view": "Zobrazení",
        "histogram": "Histogram",
        "data_table": "Tabulka dat",
        "no_data_for_histogram": "Není dostatek dat pro zobrazení histogramu",
        "probability_density": "Hustota pravděpodobnosti",
        "date": "Datum",
        "time": "Čas",
        "value": "Hodnota",
        "operator": "Operátor",
        "status": "Status",
        "prediction": "Predikce trendu",
        "trend_stable": "Trend je STABILNÍ.\nProces nemá tendenci opustit limity.",
        "trend_rising": "Trend je STOUPAJÍCÍ.",
        "trend_falling": "Trend je KLESAJÍCÍ.",
        "cross_ucl": "Pozor: Překročení UCL (Varování) za cca {n} měření.",
        "cross_usl": "KRITICKÉ: Překročení USL (Zmetky) za cca {n} měření.",
        "cross_lcl": "Pozor: Překročení LCL (Varování) za cca {n} měření.",
        "cross_lsl": "KRITICKÉ: Překročení LSL (Zmetky) za cca {n} měření.",
        "not_enough_data_pred": "Nedostatek dat pro predikci (min. {minimum} bodů).",
        "history": "Historie",
        "trend_fit": "Trend (Fit)",
        "prediction": "Predikce",
        "trend_analysis": "Analýza trendu",
        "measurements_count": "Počet měření",
        "process_status_short": "Stav procesu",
        "check_process": "Zkontrolujte proces!",
        "value_high": "Hodnota je PŘÍLIŠ VYSOKÁ!",
        "value_low": "Hodnota je PŘÍLIŠ NÍZKÁ!",
        "measured": "Naměřeno",
        "limit_usl": "Limit USL",
        "limit_lsl": "Limit LSL",
        "choose_line": "Bez výběru linky není možné pokračovat.\n\nVyberte prosím linku, na které budete měřit.",
        "save_changes": "Uložit změny",
        "count": "Počet",
        "edit_model_limits": "Úprava limitů modelu",
        "fixed_limits_enabled": "Pevné limity SPC (Zafixováno)",
        "fixed_limits": "Nastavit pevné limity SPC (UCL/LCL)",
        "fill_ucl_lcl": "Pokud jste zaškrtli pevné limity, musíte vyplnit UCL i LCL!",
        "lcl_less_than_ucl": "LCL musí být menší než UCL!",
        "target_between_lcl_ucl": "Nominální hodnota musí ležet mezi LCL a UCL!",
        "lsl_less_than_usl": "LSL musí být menší než USL!",
        "target_between_lsl_usl": "Nominální hodnota musí ležet mezi LSL a USL!",
        "limits_conflict": "Hodnoty (LCL, UCL) nejsou mezi nominální hodnotou a hodnotami (LSL, USL). Opravdu chcete pokračovat s těmito limity?",
        "lcl_below_lsl": "LCL je nižší nebo rovno LSL.",
        "ucl_above_usl": "UCL je vyšší nebo rovno USL.",
        "proceed_anyway": "Chcete tyto limity přesto uložit?",
        "model_exists": "Model s tímto názvem již existuje! Prosím zvolte jiný název modelu.",
        "choose_model_type": "Zadejte typ modelu",
        "history_title": "Nalezeno v historii",
        "history_found_msg": "Pozor! Model '{model}' byl nalezen v historii výroby.",
        "history_differs": "Jeho historické limity se liší od zadaných.",
        "history_vs_input": "Historie vs. Zadání",
        "load_history_q": "Chcete načíst a použít tyto historické limity?",
        "values_loaded_title": "Načteno",
        "values_loaded_msg": "Hodnoty byly načteny.\nZkontrolujte prosím Timer a SPC limity a stiskněte Uložit znovu.",
        "manage_operators": "Správa operátorů",
        "operators_title": "Seznam operátorů",
        "add_operator_number_placeholder": "Číslo",
        "add_operator_name_placeholder": "Jméno",
        "btn_add": "Přidat",
        "btn_delete": "Smazat",
        "confirm_delete_operator": "Opravdu smazat {jmeno}?",
        "operator_exists": "Tento operátor už existuje!",
        "operator_added": "Operátor přidán.",
        "operator_deleted": "Operátor smazán.",
        "operator_number_must_be_digit": "Číslo operátora musí být číslo!",
        "close_excel": "Zavřete prosím Excel se souborem spc_data.csv!",
        "spc_alert_msg": "VAROVÁNÍ! Naměřená hodnota je mimo kontrolní limity SPC (UCL/LCL).",
        "spc_warning": "SPC Varování",
        "spc_above": "Hodnota {value} překročila UCL ({limit}).",
        "spc_below": "Hodnota {value} klesla pod LCL ({limit}).",
        "delete_record": "Smazat záznam",
        "operator_number_and_name_required": "Musíte zadat číslo i jméno operátora!",
        "no_model_selected": "Nemáte vybraný žádný model.\n\nProsím vyberte model ze seznamu vlevo nebo vytvořte nový.",
        "btn_edit": "Editovat",
        "add_operator_number_placeholder": "Číslo",
        "add_operator_name_placeholder": "Jméno",
        "password_dialog_title": "Ověření hesla",
        "enter_password": "Zadejte heslo",
        "choose_model_first": "Nejprve vyberte model!",
        "no_data_for_model": "Tento model zatím nemá žádná data.",
        "delete_model": "Smazat model",
        "incorrect_password": "Nesprávné heslo!",
        "just_choose": "Vyberte",
        "min_one_operator": "Musí být alespoň jeden operátor! Nelze smazat posledního operátora.",
        "timer_will_reset": "Uložením změn se resetuje časovač výroby (začne Rozjezd). Opravdu chcete pokračovat?",
        "name_cant_be_changed": "Název modelu nelze v budoucnu měnit. Je název modelu správně?",
        
        
        

        

    },
    "EN": {
        "title": "SPC Monitor - Line A",
        "project": "Project",
        "shift": "Shift",
        "timer": "Next check in:",
        "btn_measure": "ADD NEW RECORD",
        "btn_exit": "EXIT",
        "lbl_operator": "Operator:",
        "lbl_value": "Measured value (g):",
        "lbl_value_without_glue": "Measured value without glue (g):",
        "lbl_value_with_glue": "Measured value with glue (g):",
        "btn_save": "SAVE RECORD",
        "btn_read_scale": "READ SCALE (BT)",
        "alert_title": "TIME TO MEASURE!",
        "spc_trend": "SPC Trend",
        "measure": "NEW MEASURE",
        "exit": "EXIT",
        "project_type": "Project Type:",
        "remaining_time": "REMAINING TIME TO MEASURE",
        "settings": "Settings",
        "language": "Language",
        "line": "Line",
        "big_title": "Glue Weight Regulation using SPC",
        "target": "Nominal Value",
        "usl": "USL",
        "lsl": "LSL",
        "timer_minutes": "Timer",
        "appearance_mode": "Appearance Mode",
        "color_theme": "Color Theme",
        "general_settings": "General Settings",
        "limits_spc": "Limits & SPC",
        "warning_limits_spc": "SPC Limits Warning",
        "error_lsl_must_be_less_usl": "Error: LSL must be less than USL!",
        "error_invalid_numbers": "Error: Invalid numbers!",
        "theme_blue": "Blue",
        "theme_dark_blue": "Dark Blue",
        "theme_green": "Green",
        "show_seconds": "Show Seconds (testing only)",
        "alert_title_shift": "Shift Warning",
        "shift_warning_message": "Current shift is not set. Please select the correct shift.",
        "add_new_model": "ADD NEW MODEL",
        "model_setup_title": "Model Setup",
        "select_model": "Select Model",
        "save_new_model": "SAVE MODEL",
        "select_model_example": "e.g. X254",
        "select_car": "Car Brand",
        "saved_models": "Saved Models:",
        "edit_model": "Edit Model",
        "delete_model": "Delete Model",
        "enter_password": "Enter Password",
        "warning_delete_model": "Are you sure you want to delete the model {model}? This action is irreversible.",
        "error_cannot_delete_active_model": "Error: Cannot delete the currently active model!",
        "warning": "Warning",
        "error": "Error",
        "confirm": "Confirm",
        "cancel": "Cancel",
        "no_model_selected": "You have not selected any model.\n\nPlease select a model from the list on the left or create a new one.",
        "calibration": "Calibration",
        "current_shift": "Current Shift: {shift_name}",
        "really_switch_model": "Really switch model?",
        "confirm_switch_model": "Are you sure you want to start production of model {model_name}?",
        "btn_save_general_setting": "SAVE GENERAL SETTINGS",
        "graph_time": "Time",
        "graph_status": "Status",
        "data_and_histogram": "Data and Histogram",
        "reset_view": " Home",
        "pan": " Move",
        "zoom": " Zoom",
        "save": "Save",
        "mode_light": "Light",
        "mode_dark": "Dark",
        "mode_system": "System",
        "input_dialog_title": "Input Dialog",
        "alert_error": "Warning",
        "error_both_weights_required": "You have to enter both weights (with and without glue)!",
        "negative_glue_weight": "Negative glue weight ({weight:.2f} g)!\nCheck if you swapped the values.",
        "load_no_glue_first": "Load no-glue weight first",
        "delete": "Delete",
        "confirm_delete": "Are you sure you want to delete this record?",
        "record_not_found": "Could not find the record in the CSV file.\nMaybe it was already deleted externally.",
        "error_writing_file": "Error writing to file",
        "confirm_delete_multiple": "Are you sure you want to delete selected records (count= {count}) ?",
        "stat_count": "Count",
        "stat_mean": "Mean",
        "stat_sigma": "Sigma (Std)",
        "stat_cp": "Cp (Potential)",
        "stat_cpk": "Cpk (Reality)",
        "stat_fix": "Fix",
        "stat_auto": "Auto",
        "data_analysis": "Data Analysis",
        "view": "View",
        "histogram": "Histogram",
        "data_table": "Data Table",
        "no_data_for_histogram": "Not enough data to display histogram",
        "probability_density": "Probability Density",
        "date": "Date",
        "time": "Time",
        "value": "Value",
        "operator": "Operator",
        "status": "Status",
        "prediction": "Trend Prediction",
        "trend_stable": "Trend is STABLE.",
        "trend_rising": "Trend is RISING.",
        "trend_falling": "Trend is FALLING.",
        "cross_ucl": "Warning: Crossing UCL in approx {n} measurements.",
        "cross_usl": "CRITICAL: Crossing USL in approx {n} measurements.",
        "cross_lcl": "Warning: Crossing LCL in approx {n} measurements.",
        "cross_lsl": "CRITICAL: Crossing LSL in approx {n} measurements.",
        "not_enough_data_pred": "Not enough data for prediction (min {minimum} points).",
        "history": "History",
        "trend_fit": "Trend (Fit)",
        "prediction": "Prediction",
        "trend_analysis": "Trend Analysis",
        "measurements_count": "Measurements Count",
        "process_status_short": "Process status",
        "check_process": "Check the process!",
        "value_high": "Value is TOO HIGH!",
        "value_low": "Value is TOO LOW!",
        "measured": "Measured",
        "limit_usl": "USL Limit",
        "limit_lsl": "LSL Limit",
        "choose_line": "Without selecting a line, you cannot proceed.\n\nPlease select the line you are currently working on.",
        "save_changes": "Save changes",
        "count": "Count",
        "edit_model_limits": "Edit model limits",
        "fixed_limits_enabled": "Fixed SPC limits (Locked)",
        "fixed_limits": "Set fixed SPC limits (UCL/LCL)",
        "fill_ucl_lcl": "If you checked fixed limits, you must fill in both UCL and LCL!",
        "lcl_less_than_ucl": "LCL must be less than UCL!",
        "target_between_lcl_ucl": "Nominal value must be between LCL and UCL!",
        "lsl_less_than_usl": "LSL must be less than USL!",
        "target_between_lsl_usl": "Nominal value must be between LSL and USL!",
        "limits_conflict": "The fixed limits you entered conflict with the calculated control limits based on current data. Please check the limits or consider collecting more data to calculate more accurate control limits.",
        "lcl_below_lsl": "LCL is less than or equal to LSL.",
        "ucl_above_usl": "UCL is greater than or equal to USL.",
        "proceed_anyway": "Do you want to save these limits anyway?",
        "lcl_below_lsl": "LCL is below or equal to LSL.",
        "ucl_above_usl": "UCL is above or equal to USL.",
        "proceed_anyway": "Do you want to save these limits anyway?",
        "model_exists": "A model with this name already exists! Please choose a different model name.",
        "choose_model_type": "Choose model type",
        "history_title": "Found in history",
        "history_found_msg": "Warning! Model '{model}' was found in production history.",
        "history_differs": "Its historical limits differ from the entered ones.",
        "history_vs_input": "History vs. Input",
        "load_history_q": "Do you want to load and use these historical limits?",
        "values_loaded_title": "Loaded",
        "values_loaded_msg": "Values have been loaded.\nPlease check the Timer and SPC limits and press Save again.",
        "manage_operators": "Manage Operators",
        "operators_title": "Operators list",
        "add_operator__number_placeholder": "Number",
        "add_operator__name_placeholder": "Name",
        "btn_add": "Add",
        "btn_delete": "Delete",
        "confirm_delete_operator": "Really delete operator {jmeno}?",
        "operator_exists": "This operator already exists!",
        "operator_added": "Operator added.",
        "operator_deleted": "Operator deleted.",
        "operator_number_must_be_digit": "Operator number must be a digit!",
        "close_excel": "Please close Excel with the spc_data.csv file!",
        "spc_alert_msg": "WARNING! The measured value is outside the SPC control limits (UCL/LCL).",
        "spc_warning": "SPC Warning",
        "spc_above": "Value {value} exceeded UCL ({limit}).",
        "spc_below": "Value {value} fell below LCL ({limit}).",
        "delete_record": "Delete record",
        "operator_number_and_name_required": "You must enter both operator number and name!",
        "no_model_selected": "You have not selected any model.\n\nPlease select a model from the list on the left or create a new one.",
        "btn_edit": "Edit operator",
        "add_operator_number_placeholder": "Number",
        "add_operator_name_placeholder": "Name",
        "password_dialog_title": "Password Verification",
        "enter_password": "Enter password",
        "choose_model_first": "Please choose a model first!",
        "no_data_for_model": "This model has no data yet.",
        "incorrect_password": "Incorrect password!",
        "just_choose": "Choose",
        "min_one_operator": "There must be at least one operator! Cannot delete the last operator.",
        "timer_will_reset": "Saving changes will reset the production timer (start-up). Do you really want to proceed?",
        "name_cant_be_changed": "The name of the model cannot be changed in the future. Is the model name correct?",
        
        
        
        
        
    },
     "UA": {
        "title": "SPC", 
        "project": "Проєкт", 
        "shift": "Зміна", 
        "timer": "Таймер", 
        "btn_measure": "НОВЕ ВИМІРЮВАННЯ", 
        "btn_exit": "Вихід", 
        "lbl_operator": "Оператор", 
        "lbl_value": "Значення (г)",
        "lbl_value_without_glue": "Значення без клею (г)", 
        "lbl_value_with_glue": "Значення з клеєм (г)", 
        "btn_save": "ЗБЕРЕГТИ ЗАПИС", 
        "btn_read_scale": "ЗЧИТАТИ ВАГУ (BT)", 
        "alert_title": "ЧАС ДЛЯ ВИМІРЮВАННЯ!", 
        "spc_trend": "Тренди SPC", 
        "measure": "НОВЕ ВИМІРЮВАННЯ", 
        "exit": "ВИХІД", 
        "project_type": "Тип проєкту", 
        "remaining_time": "ЗАЛИШИЛОСЯ ЧАСУ ДО ВИМІРЮВАННЯ", 
        "settings": "Налаштування", 
        "language": "Мова",
        "line": "Лінія",
        "big_title": "Регулювання маси клею за допомогою SPC",
        "target": "Номінальне значення",
        "usl": "USL",
        "lsl": "LSL",
        "timer_minutes": "Таймер",
        "appearance_mode": "Режим вигляду",
        "color_theme": "Колірна тема",
        "general_settings": "Загальні налаштування",
        "limits_spc": "Межі та SPC",
        "warning_limits_spc": "Попередження про межі SPC",
        "error_lsl_must_be_less_usl": "Помилка: LSL має бути менше ніж USL!",
        "error_invalid_numbers": "Помилка: Некоректні числа!",
        "theme_blue": "Синя",
        "theme_dark_blue": "Темно-синя",
        "theme_green": "Зелена",
        "show_seconds": "Показувати секунди (лише для тестування)", 
        "alert_title_shift": "Попередження про зміну",
        "shift_warning_message": "Поточну зміну не встановлено. Будь ласка, виберіть правильну зміну.",
        "add_new_model": "ДОДАТИ НОВУ МОДЕЛЬ",
        "model_setup_title": "Налаштування моделі",
        "select_model": "Модель",
        "save_new_model": "ЗБЕРЕГТИ МОДЕЛЬ",
        "select_model_example": "напр. X254",
        "select_car": "Марка автомобіля",
        "saved_models": "Збережені моделі:",
        "edit_model": "Редагувати модель",
        "delete_model": "Видалити модель",
        "enter_password": "Введіть пароль",
        "warning_delete_model": "Ви впевнені, що хочете видалити модель {model}? Цю дію неможливо скасувати.",
        "error_cannot_delete_active_model": "Помилка: Неможливо видалити поточну активну модель!",
        "warning": "Попередження",
        "error": "Помилка",
        "confirm": "Підтвердити",
        "cancel": "Скасувати",
        "no_model_selected": "Ви не вибрали жодної моделі.\n\nБудь ласка, виберіть модель зі списку зліва або створіть нову.",
        "calibration": "Калібрування",
        "current_shift": "Поточна зміна: {shift_name}",
        "really_switch_model": "Дійсно змінити модель?",
        "confirm_switch_model": "Ви впевнені, що хочете перейти на модель {model_name}? Таймер буде скинуто.",
        "btn_save_general_setting": "ЗБЕРЕГТИ ЗАГАЛЬНІ НАЛАШТУВАННЯ",
        "graph_time": "Час",
        "graph_status": "Статус",
        "data_and_histogram": "Дані та гістограма",
        "reset_view": " Головна",
        "pan": " Панорамування",
        "zoom": " Масштабування",
        "save": "Зберегти",
        "mode_light": "Світлий",
        "mode_dark": "Темний",
        "mode_system": "Системний",
        "input_dialog_title": "Діалог введення",
        "alert_error": "Попередження",
        "error_both_weights_required": "Вы должны ввести оба веса (с клеем и без клея)!",
        "negative_glue_weight": "Отрицательный вес клея ({weight:.2f} г)!\nПроверьте, не перепутали ли вы значения.",
        "load_no_glue_first": "Сначала загрузите вес без клея",
        "delete": "Удалить",
        "confirm_delete": "Вы уверены, что хотите удалить эту запись?",
        "record_not_found": "Не удалось найти запись в CSV файле.\nВозможно, она уже была удалена извне.",
        "error_writing_file": "Ошибка при записи в файл",
        "confirm_delete_multiple": "Ви впевнені, що хочете видалити вибрані записи (кількість= {count})?",
        "stat_count": "Кількість вимірювань",
        "stat_mean": "Mean (Середнє)",
        "stat_sigma": "Sigma (Станд. відх.)",
        "stat_cp": "Cp (Потенціал)",
        "stat_cpk": "Cpk (Реальність)",
        "stat_fix": "Фікс",
        "stat_auto": "Авто",
        "data_analysis": "Аналіз даних",
        "view": "Вид",
        "histogram": "Гістограма",
        "data_table": "Таблиця даних",
        "no_data_for_histogram": "Недостатньо даних для відображення гістограми",
        "probability_density": "Ймовірнісна щільність",
        "date": "Дата",
        "time": "Час",
        "value": "Значення",
        "operator": "Оператор",
        "status": "Статус",
        "prediction": "Прогноз",
        "trend_stable": "Тренд СТАБИЛЬНЫЙ.\nПроцесс не имеет тенденции покидать пределы.",
        "trend_rising": "Тренд ВОЗРАСТАЮЩИЙ.",
        "trend_falling": "Тренд ПОНИЖАЮЩИЙ.",
        "cross_ucl": "Внимание: Пересечение UCL (Предупреждение) примерно через {n} измерений.",
        "cross_usl": "КРИТИЧЕСКОЕ: Пересечение USL (Брак) примерно через {n} измерений.",
        "cross_lcl": "Внимание: Пересечение LCL (Предупреждение) примерно через {n} измерений.",
        "cross_lsl": "КРИТИЧЕСКОЕ: Пересечение LSL (Брак) примерно через {n} измерений.",
        "not_enough_data_pred": "Недостаточно данных для прогнозирования (минимум {minimum} точек).",
        "history": "История",
        "trend_fit": "Тренд (Подгонка)",
        "prediction": "Прогноз",
        "trend_analysis": "Анализ тренда",
        "measurements_count": "Количество измерений",
        "process_status_short": "Статус процесса",
        "check_process": "Проверьте процесс!",
        "value_high": "Значение слишком ВЫСОКО!",
        "value_low": "Значение слишком НИЗКО!",
        "measured": "Измерено",
        "limit_usl": "Лимит USL",
        "limit_lsl": "Лимит LSL",
        "choose_line": "Без выбора линии невозможно продолжить.\n\nПожалуйста, выберите линию, на которой вы сейчас работаете.",
        "save_changes": "Сохранить изменения",
        "count": "Количество",
        "edit_model_limits": "Редактирование лимитов модели",
        "fixed_limits_enabled": "Фиксированные лимиты SPC (Заблокировано)",
        "fixed_limits": "Установить фиксированные лимиты SPC (UCL/LCL)",
        "fill_ucl_lcl": "Если вы отметили фиксированные лимиты, вы должны заполнить как UCL, так и LCL!",
        "lcl_less_than_ucl": "LCL должен быть меньше UCL!",
        "target_between_lcl_ucl": "Цель должна быть между LCL и UCL!",
        "lsl_less_than_usl": "LSL должен быть меньше USL!",
        "target_between_lsl_usl": "Цель должна быть между LSL и USL!",
        "limits_conflict": "Введенные фиксированные лимиты конфликтуют с рассчитанными контрольными лимитами на основе текущих данных. Пожалуйста, проверьте лимиты или рассмотрите возможность сбора дополнительных данных для более точного расчета контрольных лимитов.",
        "lcl_below_lsl": "LCL ниже или равно LSL.",
        "ucl_above_usl": "UCL выше или равно USL.",
        "proceed_anyway": "Вы хотите сохранить эти лимиты в любом случае?",
        "lcl_below_lsl": "LCL ниже или равно LSL.",
        "ucl_above_usl": "UCL выше или равно USL.",
        "proceed_anyway": "Вы хотите сохранить эти лимиты в любом случае?",
        "model_exists": "Модель с таким именем уже существует! Пожалуйста, выберите другое имя модели.",
        "choose_model_type": "Выберите тип модели",
        "history_title": "Найдено в истории",
        "history_found_msg": "Внимание! Модель '{model}' была найдена в истории производства.",
        "history_differs": "Ее исторические лимиты отличаются от введенных.",
        "history_vs_input": "История vs. Ввод",
        "load_history_q": "Вы хотите загрузить и использовать эти исторические лимиты?",
        "values_loaded_title": "Загружено",
        "values_loaded_msg": "Значения были загружены.\nПожалуйста, проверьте Timer и лимиты SPC и нажмите Сохранить снова.",
        "manage_operators": "Управление операторами",
        "operators_title": "Список операторов",
        "add_operator_name_placeholder": "Имя",
        "add_operator_number_placeholder": "Номер",
        "btn_add": "Добавить",
        "btn_delete": "Удалить",
        "confirm_delete_operator": "Действительно удалить оператора {jmeno}?",
        "operator_exists": "Этот оператор уже существует!",
        "operator_added": "Оператор добавлен.",
        "operator_deleted": "Оператор удален.",
        "operator_number_must_be_digit": "Номер оператора должен быть числом!",
        "close_excel": "Пожалуйста, закройте Excel с файлом spc_data.csv!",
        "spc_alert_msg": "ВНИМАНИЕ! Измеренное значение находится за пределами контрольных лимитов SPC (UCL/LCL).",
        "spc_warning": "SPC Предупреждение",
        "spc_above": "Значение {value} превысило UCL ({limit}).",
        "spc_below": "Значение {value} упало ниже LCL ({limit}).",
        "delete_record": "Удалить запись",
        "operator_number_and_name_required": "Вы должны ввести как номер, так и имя оператора!",
        "no_model_selected": "Вы не выбрали ни одной модели.\n\nПожалуйста, выберите модель из списка слева или создайте новую.",
        "btn_edit": "Редактировать оператора",
        "add_operator_number_placeholder": "Номер",
        "add_operator_name_placeholder": "Имя",
        "password_dialog_title": "Проверка пароля",
        "enter_password": "Введите пароль",
        "choose_model_first": "Сначала выберите модель!",
        "no_data_for_model": "У этой модели пока нет данных.",
        "just_choose": "Выберите",
        "incorrect_password": "Неверный пароль!",
        "delete_model": "Удалить модель",
        "min_one_operator": "Должен быть хотя бы один оператор! Невозможно удалить последнего оператора.",
        "timer_will_reset": "Сохранение изменений сбросит таймер производства (начнется Разогрев). Вы действительно хотите продолжить?",
        "name_cant_be_changed": "Имя модели не может быть изменено в будущем. Имя модели указано верно?"
        


        

        },          

    "RO": {"title": "SPC", 
           "project": "Proiect", 
           "shift": "Schimb", 
            "timer": "Timer",
            "btn_measure": "Masurare",
            "btn_exit": "Iesire",
            "lbl_operator": "Operator",
            "lbl_value": "Valoare (g)",
            "lbl_value_without_glue": "Valoare fără adeziv (g)",
            "lbl_value_with_glue": "Valoare cu adeziv (g)",
            "btn_save": "Salveaza",
            "btn_read_scale": "Cantar",
            "alert_title": "Alertă",
            "spc_trend": "Tendință",
            "measure": "Masurare",
            "exit": "Iesire",
            "project_type": "Tip",
            "remaining_time": "Timp pana la masurare",
            "settings": "Setări",   
            "language": "Limbă",
            "line": "Linie",
            "big_title": "Regulare a greutății adezivului folosind SPC",
            "target": "Valoare nominală",
            "usl": "USL",
            "lsl": "LSL",
            "timer_minutes": "Temporizator",
            "appearance_mode": "Mod de aspect",
            "color_theme": "Temă de culoare",
            "general_settings": "Setări generale",
            "limits_spc": "Limite & SPC",
            "warning_limits_spc": "Avertisment limite SPC",
            "error_lsl_must_be_less_usl": "Eroare: LSL trebuie să fie mai mic decât USL!",
            "error_invalid_numbers": "Eroare: Numere invalide!",
            "theme_blue": "Albastru",
            "theme_dark_blue": "Albastru închis",
            "theme_green": "Verde",
            "show_seconds": "Afișați secundele (doar testare)",
            "alert_title_shift": "Avertisment schimb",
            "shift_warning_message": "Schimbul curent nu este setat. Vă rugăm să selectați schimbul corect.",
            "add_new_model": "ADAUGĂ UN NOU MODEL",
            "model_setup_title": "Setare model",
            "select_model": "Model",
            "select_model_example": "ex. X254",
            "save_new_model": "SALVEAZĂ MODEL",
            "select_car": "Marca mașinii",
            "saved_models": "Modele salvate:",
            "edit_model": "Editează model",
            "delete_model": "Șterge model",
            "enter_password": "Introduceți parola",
            "warning_delete_model": "Sunteți sigur că doriți să ștergeți modelul {model}? Această acțiune este ireversibilă.",
            "error_cannot_delete_active_model": "Eroare: Nu se poate șterge modelul activ curent!",
            "warning": "Avertisment",
            "error": "Eroare",
            "confirm": "Confirmare",
            "cancel": "Anulare",
            "no_model_selected": "Nu ați selectat niciun model.\n\nVă rugăm să selectați un model din lista din stânga sau să creați unul nou.",
            "calibration": "Calibrare",
            "current_shift": "Schimb curent: {shift_name}",
            "really_switch_model": "Sigur doriți să schimbați modelul?",
            "confirm_switch_model": "Sigur doriți să începeți producția modelului {model_name}?",
            "btn_save_general_setting": "SALVEAZĂ SETĂRILE GENERALE",
            "graph_time": "Timp",
            "graph_status": "Status",
            "data_and_histogram": "Date și histogramă",
            "reset_view": " Acasă",
            "pan": " Panoramare",
            "zoom": " Zoom",
            "save": "Salvează",
            "mode_light": "Luminos",
            "mode_dark": "Întunecat",
            "mode_system": "Sistem",
            "input_dialog_title": "Dialog de intrare",
            "alert_error": "Avertisment",
            "error_both_weights_required": "Trebuie să introduceți ambele greutăți (cu și fără adeziv)!",
            "negative_glue_weight": "Greutate negativă a adezivului ({weight:.2f} g)!\nVerificați dacă ați inversat valorile.",
            "load_no_glue_first": "Încărcați mai întâi greutatea fără adeziv",
            "delete": "Șterge",
            "confirm_delete": "Sigur doriți să ștergeți această înregistrare?",
            "record_not_found": "Nu s-a putut găsi înregistrarea în fișierul CSV.\nPoate a fost deja șters extern.",
            "error_writing_file": "Eroare la scrierea în fișier",
            "confirm_delete_multiple": "Sunteți sigur că doriți să ștergeți înregistrările selectate (număr= {count})?",
            "stat_count": "Număr măsurători",
            "stat_mean": "Mean (Medie)",
            "stat_sigma": "Sigma (Std)",
            "stat_cp": "Cp (Potențial)",
            "stat_cpk": "Cpk (Realitate)",
            "stat_fix": "Fix",
            "stat_auto": "Auto",
            "data_analysis": "Analiza datelor",
            "view": "Vizualizare",
            "histogram": "Histogramă",
            "data_table": "Tabel de date",
            "no_data_for_histogram": "Nu sunt suficiente date pentru a afișa histograma",
            "probability_density": "Densitatea probabilității",
            "date": "Data",
            "time": "Ora",
            "value": "Valoare",
            "operator": "Operator",
            "status": "Status",
            "prediction": "Predicție tendință",
            "trend_stable": "Tendința este STABILĂ.\nProcesul nu are tendința de a părăsi limitele.",
            "trend_rising": "Tendința este ÎN CREȘTERE.",
            "trend_falling": "Tendința este ÎN SCĂDERE.",
            "cross_ucl": "Atenție: Traversarea UCL în aproximativ {n} măsurători.",
            "cross_usl": "CRITIC: Traversarea USL în aproximativ {n} măsurători.",
            "cross_lcl": "Atenție: Traversarea LCL în aproximativ {n} măsurători.",
            "cross_lsl": "CRITIC: Traversarea LSL în aproximativ {n} măsurători.",
            "not_enough_data_pred": "Nu sunt suficiente date pentru predicție (min. {minimum} puncte).",
            "history": "Istoric",
            "trend_fit": "Tendință (Ajustare)",
            "prediction": "Predicție",
            "trend_analysis": "Analiza tendinței",
            "measurements_count": "Număr măsurători",
            "process_status_short": "Status proces",
            "check_process": "Verificați procesul!",
            "value_high": "Valoarea este PREA MARE!",
            "value_low": "Valoarea este PREA MICĂ!",
            "measured": "Măsurat",
            "limit_usl": "Limită USL",
            "limit_lsl": "Limită LSL",
            "choose_line": "Fără a selecta o linie, nu puteți continua.\n\nVă rugăm să selectați linia pe care lucrați în prezent.",
            "save_changes": "Salvează modificările",
            "count": "Număr",
            "edit_model_limits": "Editare limite model",
            "fixed_limits_enabled": "Limite SPC fixe (Blocat)",
            "fixed_limits": "Setați limite SPC fixe (UCL/LCL)",
            "fill_ucl_lcl": "Dacă ați bifat limite fixe, trebuie să completați atât UCL, cât și LCL!",
            "lcl_less_than_ucl": "LCL trebuie să fie mai mic decât UCL!",
            "target_between_lcl_ucl": "Target trebuie să fie între LCL și UCL!",
            "lsl_less_than_usl": "LSL trebuie să fie mai mic decât USL!",
            "target_between_lsl_usl": "Target trebuie să fie între LSL și USL!",
            "limits_conflict": "Limitele fixe pe care le-ați introdus intră în conflict cu limitele de control calculate pe baza datelor actuale. Vă rugăm să verificați limitele sau să colectați mai multe date pentru a calcula limite de control mai precise.",
            "lcl_below_lsl": "LCL este sub sau egal cu LSL.",
            "ucl_above_usl": "UCL este peste sau egal cu USL.",
            "proceed_anyway": "Doriți să salvați aceste limite oricum?",
            "model_exists": "Un model cu acest nume există deja! Vă rugăm să alegeți un nume de model diferit.",
            "choose_model_type": "Alegeți tipul de model",
            "history_title": "Găsit în istoric",
            "history_found_msg": "Atenție! Modelul '{model}' a fost găsit în istoricul de producție.",
            "history_differs": "Limitele istorice diferă de cele introduse.",
            "history_vs_input": "Istoric vs. Introducere",
            "load_history_q": "Doriți să încărcați și să utilizați aceste limite istorice?",
            "values_loaded_title": "Încărcat",
            "values_loaded_msg": "Valorile au fost încărcate.\nVă rugăm să verificați Timerul și limitele SPC și să apăsați din nou Salvare.",
            "manage_operators": "Gestionați operatorii",
            "operators_title": "Lista de operatori",
            "add_operator_name_placeholder": "Nume",
            "add_operator_number_placeholder": "Număr",
            "btn_add": "Adăugați",
            "btn_delete": "Eliminați",
            "confirm_delete_operator": "Sigur doriți să ștergeți operatorul {jmeno}?",
            "operator_exists": "Acest operator există deja!",
            "operator_added": "Operator adăugat.",
            "operator_deleted": "Operator șters.",
            "operator_number_must_be_digit": "Numărul operatorului trebuie să fie o cifră!",
            "close_excel": "Vă rugăm să închideți Excel cu fișierul spc_data.csv!",
            "spc_alert_msg": "ATENȚIE! Valoarea măsurată este în afara limitelor de control SPC (UCL/LCL).",
            "spc_warning": "Avertisment SPC",
            "spc_above": "Valoarea {value} a depășit UCL ({limit}).",
            "spc_below": "Valoarea {value} a scăzut sub LCL ({limit}).",
            "delete_record": "Ștergeți înregistrarea",
            "operator_number_and_name_required": "Trebuie să introduceți atât numărul, cât și numele operatorului!",
            "no_model_selected": "Nu ați selectat niciun model.\n\nVă rugăm să selectați un model din lista din stânga sau să creați unul nou.",
            "btn_edit": "Editați operator",
            "add_operator_number_placeholder": "Număr",
            "add_operator_name_placeholder": "Nume",
            "password_dialog_title": "Verificare parolă",
            "enter_password": "Introduceți parola",
            "choose_model_first": "Vă rugăm să alegeți un model mai întâi!",
            "no_data_for_model": "Acest model nu are încă date.",
            "just_choose": "Alegeți",
            "incorrect_password": "Parolă incorectă!",
            "delete_model": "Ștergeți modelul",
            "min_one_operator": "Trebuie să existe cel puțin un operator! Nu se poate șterge ultimul operator.",
            "timer_will_reset": "Salvarea modificărilor va reseta timerul de producție (începe faza de încălzire). Doriți să continuați?",
            "name_cant_be_changed": "Numele modelului nu poate fi schimbat în viitor. Este numele modelului corect?"
            
    }
}